### PR TITLE
Feature issue 175

### PR DESCRIPTION
**Pull request by iravimandalia**
Fix code smells related #182 

Close #182

### CODE REVIEW

**Review by mepox — APPROVED** [review]

**Comment by mepox** [comment]
Hi @iravimandalia ! Thanks for noticing this 👍  I saw it as well and was about to open a new issue 😅

**Comment by iravimandalia** [comment]
Yeah, I noticed it lately and configured sonarlint on my IDE to find such issues before pushing the changes.

**Comment by mepox** [comment]
Nice, I haven't heard about SonarLint before. We have the SonarCloud Bot here that is commenting on every PRs re the quality of the code.

**Comment by iravimandalia** [comment]
I use this [sonarlint plugin](https://plugins.jetbrains.com/plugin/7973-sonarlint) for Intellij. It's the same as SonarQube or SonarCloud.

**Pull request merged**
