### PR TITLE
 remove public access modifier in RegisterControllertest and Changed the visibility of this constructor to "protected" in GenericCrudService.java.

### LINKED ISSUE #66: Change the visibility of this constructor to "protected" in `GenericCrudService.java`
[Sonar link issue](https://sonarcloud.io/project/issues?issues=AYQT58_wwxsCzz419tCm&open=AYQT58_wwxsCzz419tCm&id=fitbuddy-app)

https://github.com/mepox/fitbuddy/blob/06e709035af18062e0f1e7e1d4d72b27be4cf0be/src/main/java/com/laszlojanku/fitbuddy/jpa/service/GenericCrudService.java#L12

### LINKED ISSUE #81: Remove this 'public' modifier in `RegisterControllerTest`
[Sonar issue link](https://sonarcloud.io/project/issues?fileUuids=AYRSl9tbCoA7H_qQ4mB4&resolved=false&rules=java%3AS5786&severities=INFO&types=CODE_SMELL&id=fitbuddy-app&open=AYRSl92tCoA7H_qQ4mB-)

https://github.com/mepox/fitbuddy/blob/40b1a8787682fdbfb12db92c04c5c05faee839d0/src/test/java/com/laszlojanku/fitbuddy/operation/controller/RegisterControllerTest.java#L30

https://github.com/mepox/fitbuddy/blob/40b1a8787682fdbfb12db92c04c5c05faee839d0/src/test/java/com/laszlojanku/fitbuddy/operation/controller/RegisterControllerTest.java#L38

https://github.com/mepox/fitbuddy/blob/40b1a8787682fdbfb12db92c04c5c05faee839d0/src/test/java/com/laszlojanku/fitbuddy/operation/controller/RegisterControllerTest.java#L54

https://github.com/mepox/fitbuddy/blob/40b1a8787682fdbfb12db92c04c5c05faee839d0/src/test/java/com/laszlojanku/fitbuddy/operation/controller/RegisterControllerTest.java#L65

### PR DESCRIPTION
**Pull request by SwethaTamatam**
Removed the public access modifier in RegisterControllertest at mentioned places and Changed the visibility of this constructor to "protected" in GenericCrudService.java. Please let me know if there are any changes. 
Close #81 
Close #66

### CODE REVIEW

**Review by mepox — APPROVED** [review]

**Comment by mepox** [comment]
Hi @SwethaTamatam ! Thanks for your contribution. I see you committed both changes into one PR. This is fine for now as both tasks were small, but for a better workflow it's always better to open a separate PR for each issues. Nonetheless, the PR looks good and this will be merged soon 🎉

**Comment by mepox** [comment]
@all-contributors add @SwethaTamatam for code

**Comment by SwethaTamatam** [comment]
> Hi @SwethaTamatam ! Thanks for your contribution. I see you committed both changes into one PR. This is fine for now as both tasks were small, but for a better workflow it's always better to open a separate PR for each issues. Nonetheless, the PR looks good and this will be merged soon 🎉

Thank you @mepox for giving me the chance to contribute. I will make sure next time I wont do multiple commits into one PR.

**Comment by mepox** [comment]
@SwethaTamatam Of course, I am sure there will be more issues up for grabs in the near future 😅 Thanks again 👍

**Pull request merged**
